project:
  type: website
  output-dir: docs

website:
  title: "Disparities in Breast and Cervical Outcomes"
  navbar:
    left:
      - href: index.qmd
        text: Project Home
      - href: About Me.qmd
        text: About Me
      - href: About The Cancers.qmd
        text: About the Cancers
      - href: Disparities and Why They Exist.qmd
        text: Disparities and Why They Exist
      - href: Data and Key Findings.qmd
        text: Data and Key Findings
      - href: Prevention and Screening.qmd
        text: Prevention and Screening
      - href: Resources and Recommendations.qmd
        text: Resources and Recommendations

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true

editor: visual

